#!/usr/bin/env bash

# Shared paths for the single-GPU AutoDL/SeetaCloud workspace.
# Every value can be overridden by exporting it before sourcing this file.

SOMBENCH_ROOT="${SOMBENCH_ROOT:-/root/autodl-tmp/sombench}"
SOMBENCH_PROJECT_DIR="${SOMBENCH_PROJECT_DIR:-${SOMBENCH_ROOT}/project}"
SOMBENCH_DATA_DIR="${SOMBENCH_DATA_DIR:-${SOMBENCH_ROOT}/datasets}"
SOMBENCH_MODEL_DIR="${SOMBENCH_MODEL_DIR:-${SOMBENCH_ROOT}/models/Qwen3-14B}"
SOMBENCH_OUTPUT_DIR="${SOMBENCH_OUTPUT_DIR:-${SOMBENCH_ROOT}/outputs}"
SOMBENCH_MERGED_DIR="${SOMBENCH_MERGED_DIR:-${SOMBENCH_ROOT}/merged_model}"
SOMBENCH_RELEASE_DIR="${SOMBENCH_RELEASE_DIR:-${SOMBENCH_ROOT}/release_model}"
SOMBENCH_LOG_DIR="${SOMBENCH_LOG_DIR:-${SOMBENCH_ROOT}/logs}"
SOMBENCH_CACHE_DIR="${SOMBENCH_CACHE_DIR:-${SOMBENCH_ROOT}/cache}"
SOMBENCH_TMP_DIR="${SOMBENCH_TMP_DIR:-${SOMBENCH_ROOT}/tmp}"
SOMBENCH_WHEELHOUSE="${SOMBENCH_WHEELHOUSE:-${SOMBENCH_ROOT}/downloads}"
SOMBENCH_HUB_ENV="${SOMBENCH_HUB_ENV:-${SOMBENCH_ROOT}/envs/hub}"
SOMBENCH_TRAIN_ENV="${SOMBENCH_TRAIN_ENV:-${SOMBENCH_ROOT}/envs/train}"
SOMBENCH_EVAL_ENV="${SOMBENCH_EVAL_ENV:-${SOMBENCH_ROOT}/envs/eval}"

export SOMBENCH_ROOT SOMBENCH_PROJECT_DIR SOMBENCH_DATA_DIR SOMBENCH_MODEL_DIR
export SOMBENCH_OUTPUT_DIR SOMBENCH_MERGED_DIR SOMBENCH_RELEASE_DIR SOMBENCH_LOG_DIR
export SOMBENCH_CACHE_DIR SOMBENCH_TMP_DIR SOMBENCH_HUB_ENV SOMBENCH_TRAIN_ENV SOMBENCH_EVAL_ENV
export SOMBENCH_WHEELHOUSE

export HF_HOME="${HF_HOME:-${SOMBENCH_CACHE_DIR}/huggingface}"
export HUGGINGFACE_HUB_CACHE="${HUGGINGFACE_HUB_CACHE:-${HF_HOME}/hub}"
export MODELSCOPE_CACHE="${MODELSCOPE_CACHE:-${SOMBENCH_CACHE_DIR}/modelscope}"
export MODELSCOPE_HOME="${MODELSCOPE_HOME:-${SOMBENCH_CACHE_DIR}/modelscope-home}"
export PIP_CACHE_DIR="${PIP_CACHE_DIR:-${SOMBENCH_CACHE_DIR}/pip}"
export TORCH_HOME="${TORCH_HOME:-${SOMBENCH_CACHE_DIR}/torch}"
export TMPDIR="${TMPDIR:-${SOMBENCH_TMP_DIR}}"
export TOKENIZERS_PARALLELISM="${TOKENIZERS_PARALLELISM:-false}"
export PYTHONUNBUFFERED="${PYTHONUNBUFFERED:-1}"
